### ISSUE TITLE
Better support for more logging levels (WARN, ERROR, FATAL)

### ISSUE THREAD

**Issue by binkley** [mjstrasser/ktlogging#2]
Strange as it may seem, some folks will want to hide WARN level logging (not my cup of tea, but a general-purpose library should cater to all tastes).  Some extremists might even want logic for ERROR or FATAL levels.

In particular, `BaseLogger` should have functions: `isWarnEnabled()`, `isErrorEnabled()`, `isFatalEnabled()`

**Comment by mjstrasser** [comment]
Thanks, will do.

**Comment by mjstrasser** [comment]
Done.
