### ISSUE TITLE
Build should auto-format code to standard Kotlin conventions

### ISSUE THREAD

**Issue by binkley** [mjstrasser/ktlogging#3]
An example: Standard Kotlin convention is to /not/ have a blank line after opening a class declaration.  If this project wants to follow the blank line convention, it should be explicit.

Ktlint is a good Gradle plugin for automating formatting: https://github.com/pinterest/ktlint

**Comment by mjstrasser** [comment]
Thanks @binkley 

I will soon bring in standards like those recommended by your excellent [Modern Java Practices](https://github.com/binkley/modern-java-practices).
